name: Light Client Layer

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - qa
      - dev
    paths:
      - 'layers/**'
      - '.github/workflows/light_client.yml'

jobs:
  create_layer:
    name: create_layer
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Create Layer Logic
        shell: bash
        run: |
          echo "Layer Created"
